version: "3.8"

networks:
  vpn:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /mnt/media/servarr/qbittorrent/config:/config
      - /mnt/media/servarr/downloads:/data/downloads
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file:
      - ../env/proton.env
    ports:
      - 8080:8080       # qBittorrent Web UI
      - 8999:8999       # TCP torrent
      - 8999:8999/udp   # UDP torrent
    networks:
      vpn:
        aliases:
          - gluetun
        ipv4_address: 192.168.100.2
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
    volumes:
      - /mnt/media/servarr/radarr/config:/config
      - /mnt/media/servarr/movies:/movies
      - /mnt/media/servarr/downloads:/data/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
    volumes:
      - /mnt/media/servarr/sonarr/config:/config
      - /mnt/media/servarr/downloads:/data/downloads
      - /mnt/media/servarr/tv:/tv
      - /mnt/media/servarr/anime:/anime
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
    volumes:
      - /mnt/media/servarr/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
    volumes:
      - /mnt/media/servarr/jellyseerr/config:/app/config
      - /mnt/media/servarr/movies:/movies
      - /mnt/media/servarr/tv:/tv
      - /mnt/media/servarr/anime:/anime
    ports:
      - 5055:5055
    restart: unless-stopped

