version: "3.8"

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=545
      - TZ=America/New_York
    volumes:
      - /root/servarr/config/jellyfin/config:/config
      - /mnt/media/servarr/downloads:/data/downloads
      - /mnt/media/servarr/movies:/movies
      - /mnt/media/servarr/tv:/tv
      - /mnt/media/servarr/anime:/anime
    ports:
      - 10.10.0.2:8096:8096
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

